dist: trusty
sudo: required
language: node_js
node_js:
- '4'
- '6'
- '8'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage
after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && `node --version` == *v8* ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
env:
  global:
    secure: bu1VaFjYzaCxhMusdlJ2OTjHqfxVBECVI1m5B1FBRnBtqYTugwrJ9w3F91Yk0P6RpsbSRr+ksk/FsgwPiwJUlrwO9CN5ANFeqsBZa/GZXModKOrbMjgqfbdOYxUuZ/czUDjMwLfBt8/6NXBYE/hpffvOWFnp8l5HxhTjq6MyLDNC7MJ2Bmf+r9qEbAXWhsz6LVCkuWYnulbv8PCaGaIfuoPdmuXvWGTmGBw/6Fg4uc8dysk/E6Smz/5Aj+kAz3/bZUrARCP8QIXiyi23G4FKzMgq4YnRdQmkESE6UYZbkjev+9hBTh5cBQx8irWCiDWX7LhTJ4+E71tFLVnWjbek6HuqnCRR0RMuNg2n1/zBv3M1gRP2ZEK6An699QlSbKsPICU0oNdqkoicmh1AHfgYUoNukLla//6mijul3o+VyxZk8bgxpO+1ZbaTvCGjzqVGBGmg1FZpF8AjqWmxKlgXrwXM9J+XGqeFBdX3D+9CM+kcYL8lnEDADAeA7N9jH9mcV+CT19VNSPymRUZImIh9krpo6Nqg7+jySPMAUkMbaoUgoZ4YryWhG8buzOhRY9N+/P+MpYNuxy1Kp36wEyk/V1pcVoh5NQGcjmV6mPCyBip7wj8IOjIlUuyWwTbfm2nTQ+el8q463XNiFBPwwSBqIUOHj/UU1VZ4UgGylAhLGac=
